name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint_test_scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v1

    - name: Install dependencies
      run: uv pip install --system --quiet .[dev]

    - name: Check formatting with Ruff
      run: uv run --quiet ruff format --check .

    - name: Lint with Ruff
      run: uv run --quiet ruff check .

    - name: Run tests with Pytest
      run: uv run --quiet pytest

    - name: Run security scan with Bandit
      run: uv run --quiet bandit -r pyakta 